### ISSUE TITLE
Referencing

### ISSUE THREAD

**Issue by jhdark** [alfkoehn/fusion_plots#4]
Hi @alfkoehn and @jhillairet

I would like to use these lovely plots in my thesis, just wondering if you would like a reference to this repository?

**Comment by alfkoehn** [comment]
Hi @jhdark ,

happy to hear that you are using the plots :)

A reference to the released package, see the doi, would be nice and is greatly appreciated. The doi is 10.5281/zenodo.4946068
(This is the latest release of the package and it also points to this repository, so referencing this doi makes most sense).
