### ISSUE TITLE
Evolution of triple product record vs year

### ISSUE THREAD

**Issue by hattom** [alfkoehn/fusion_plots#6]
Hi Alf,

I've seen a number of presentations over the years which show the triple-product record vs time.
These are then often compared to, e.g. Moore's law.

Do any of the triple-product datasets contain year information, or would you know where to find the data for this?

If I know where to get the data, I would volunteer a PR with the figure.

Cheers,
Thomas

**Comment by jhillairet** [comment]
I don't think so, but I'm asking : @RemDelaporteMathurin, do you have the date at which the triple product values in your data have been obtained in https://github.com/RemDelaporteMathurin/fusion-world ?

**Comment by RemDelaporteMathurin** [comment]
> I don't think so, but I'm asking : @RemDelaporteMathurin, do you have the date at which the triple product values in your data have been obtained in https://github.com/RemDelaporteMathurin/fusion-world ?

It does not no. Although this would be a great addition to Fusion-World! Keep me posted :-)

**Comment by hattom** [comment]
https://iopscience.iop.org/article/10.1088/0031-9120/38/2/305
All roads seem to bring me back to the version in the above paper by Anthony J Webster, whose caption, in turn, says that the original version was made by J B Lister (EPFL) and M Greenwald (MIT).

**Comment by alfkoehn** [comment]
@hattom I also always ended up with the Webster paper (and the corresponding comment to a plot made my Lister & Greenwald) and I already have that plot re-made sitting on my harddrive (for usage in my lectures), so I will add this plot to the repository next. As soon as I have added the plot, I will close this issue

@RemDelaporteMathurin nice way of show-casing the fusion world, really like that!

**Comment by RemDelaporteMathurin** [comment]
@alfkoehn keep me posted, I'm really interested in adding this plot to fusion-world too, and make an interactive version of it :-)

**Comment by alfkoehn** [comment]
@hattom @RemDelaporteMathurin I've added a plot of the triple product vs time to the repository [1]. Funny side note: the doubling rate I get from fitting the data varies slightly from the value stated in the papers. Note that at the moment, it is just the dataset from the papers extracted from the plot. For the future, I plane to add a "self-made database", i.e. digging out all the values from the literature with including all the proper references. 

But for now, I would close this issue - let me know if there are any issues with this plot.

[1] https://github.com/alfkoehn/fusion_plots/tree/master/triple_product_vs_time
